# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@4.7.0

workflows:
  mend-workflow:
    jobs:
      - example-mend-job:
          context:
            - Mend

jobs:
  example-mend-job:
    docker:
      # prebuilt image with java
      - image: cimg/openjdk:16.0.2
    steps:
      # checkout git
      - checkout
      # install node/npm
      - node/install
      # npm install packages
      - node/install-packages
      - run: 
          name: Download Mend CLI
          command: sudo curl "https://ws-cli.s3.amazonaws.com/44/linux_amd64/ws" -o "/usr/local/bin/ws" && sudo chmod +x "/usr/local/bin/ws"
      - run: 
          name: Authenticate and Run Mend CLI
          command: |
            ws auth login --user-key $USER_KEY --url https://saas.mend.io --email sam.quakenbush@whitesourcesoftware.com
            ws scan -u -s SamQDemoCorp-Dev//<<CIRCLE_PROJECT_REPONAME>>//<<pipeline.git.branch>>
